Repository PyeongSaeng/PyeongSaeng-FE, pull requests merged in 2025-07, with the labels that each got.

#10 [fix] remove unused React import
  .github/workflows/deploy.yml
  src/App.tsx
Labels: fix, 보미

#28 [feat] 로그인 전 홈화면 ui
  package.json
  pnpm-lock.yaml
  src/index.css
  src/pages/Personal/Home.tsx
  src/shared/assets/popular-dummy1.png
  src/shared/components/topbar/MenuButton.tsx
  src/shared/components/topbar/Test.tsx
Labels: feature, 보미

#32 [feat] 드릴다운 메뉴 구현
  package.json
  src/index.css
  src/pages/Personal/ExtraQuestionsPage.tsx
  src/pages/Personal/HomePage.tsx
  src/pages/Personal/QuestionDetailPage.tsx
  src/routes/index.tsx
  src/shared/components/buttons/GreenButton.tsx
  src/shared/components/buttons/OptionButton.tsx
  src/shared/components/topbar/MenuButton.tsx
  src/shared/components/topbar/QuestionButton.tsx
  src/shared/components/topbar/Test.tsx
  src/shared/components/topbar/Topbar.tsx
  src/shared/components/topbar/menu/Menu.tsx
  src/shared/components/topbar/menu/MenuNavButton.tsx
  src/shared/components/topbar/menu/company-menu/MainMenu.tsx
  src/shared/components/topbar/menu/personal-menu/GuardianMyMenu.tsx
  src/shared/components/topbar/menu/personal-menu/MainMenu.tsx
  src/shared/components/topbar/menu/personal-menu/SeniorMyMenu.tsx
Labels: feature, 보미

#57 [feat] 기업 일자리 신청 이미지 첨부, 지역 선택 기능 추가
  index.html
  src/pages/Company/CompanyCreateJobPage.tsx
  src/pages/Personal/JobApplyPage.tsx
  src/pages/Personal/JobRecommendationPage.tsx
  src/shared/components/AddressSearchInput.tsx
  src/shared/components/EvidenceSection/FileDropZone.tsx
  src/shared/components/EvidenceSection/ImageUploadButton.tsx
  src/shared/components/EvidenceSection/index.tsx
  src/shared/hooks/usePasteUpload.tsx
Labels: feature, refactor, 보경

#54 [feat] company ApplicationsPage UI 구현
  .pnpm-lock 2.yaml.icloud
  pnpm-lock.yaml
  src/App.tsx
  src/pages/Company/ApplicationDetailPage.tsx
  src/pages/Company/ApplicationResultsPage.tsx
  src/pages/Company/ApplicationsPage.tsx
  src/routes/index 2.tsx
  src/routes/index.tsx
  src/shared/components/Button.tsx
  src/shared/components/Field.tsx
  src/shared/components/PageHeader.tsx
  src/shared/components/topbar/Logo 2.tsx
  src/shared/components/topbar/QuestionButton 2.tsx
  src/shared/components/topbar/ToggleButton 2.tsx
  src/shared/components/topbar/Topbar 2.tsx
  src/shared/constants/applicationData.ts
  tailwind.config.js
Labels: feature, 연수

#55 [feat] 어르신 직접 회원가입, 기업 로그인/회원가입, 아이디/비밀번호 수정 UI 구현
  .gitignore
  pnpm-lock.yaml
  src/App.tsx
  src/index.css
  src/pages/Company/CompanyLogin.tsx
  src/pages/Company/CompanySignin.tsx
  src/pages/Company/components/FindAccount/FindAccount.tsx
  src/pages/Company/components/FindAccount/IdFind.tsx
  src/pages/Company/components/FindAccount/PasswordFind.tsx
  src/pages/Company/types/company.ts
  src/pages/Personal/Login.tsx
  src/pages/Personal/LoginMain.tsx
  src/pages/Personal/SignIn.tsx
  src/pages/Personal/components/.gitkeep
  src/pages/Personal/components/user/FindAccount/FindAccount.tsx
  src/pages/Personal/components/user/FindAccount/IdFind.tsx
  src/pages/Personal/components/user/FindAccount/PasswordFind.tsx
  src/pages/Personal/components/user/signIn/Care/CareSignIn.tsx
  src/pages/Personal/components/user/signIn/Care/CareStep1.tsx
  src/pages/Personal/components/user/signIn/Care/CareStep2.tsx
  src/pages/Personal/components/user/signIn/Care/CareStep3.tsx
  src/pages/Personal/components/user/signIn/Care/CareStep4.tsx
  src/pages/Personal/components/user/signIn/Care/CareStep5.tsx
  src/pages/Personal/components/user/signIn/NextButton.tsx
  src/pages/Personal/components/user/signIn/Senior/SeniorSignIn.tsx
  src/pages/Personal/components/user/signIn/Senior/SeniorStep1.tsx
  src/pages/Personal/components/user/signIn/Senior/SeniorStep2.tsx
  src/pages/Personal/components/user/signIn/Senior/SeniorStep3.tsx
  src/pages/Personal/components/user/signIn/SignUpHeader.tsx
  src/pages/Personal/types/user.ts
  src/pages/Personal/user/Login.tsx
  src/pages/Personal/user/LoginMain.tsx
  src/pages/Personal/user/signIn/Care/CareStep1.tsx
  src/pages/Personal/user/signIn/Care/CareStep5.tsx
  src/pages/Personal/user/signIn/Senior/SeniorSignIn.tsx
  src/pages/Personal/user/signIn/SignIn.tsx
  src/routes/index 2.tsx
  src/routes/index.tsx
Labels: feature, style, 소이

#61 [fix] 기업-받은 신청서 페이지 중복된 라우트 제거
  .pnpm-lock 2.yaml.icloud
  pnpm-lock.yaml
  src/routes/index.tsx
  src/shared/components/topbar/menu/company-menu/MainMenu.tsx
Labels: fix, 연수
