Repository PyeongSaeng/PyeongSaeng-FE, pull requests merged in 2025-08, with the labels that each got.

#66 [feat] 일반 사용자 로그인 및 회원가입 api 연동
  src/pages/Personal/Login.tsx
  src/pages/Personal/apis/auth.ts
  src/pages/Personal/components/user/signIn/Care/CareSignIn.tsx
  src/pages/Personal/components/user/signIn/Care/CareStep1.tsx
  src/pages/Personal/components/user/signIn/Care/CareStep2.tsx
  src/pages/Personal/components/user/signIn/Care/CareStep3.tsx
  src/pages/Personal/components/user/signIn/Care/CareStep5.tsx
  src/pages/Personal/components/user/signIn/Senior/SeniorSignIn.tsx
  src/pages/Personal/components/user/signIn/Senior/SeniorStep1.tsx
  src/pages/Personal/components/user/signIn/Senior/SeniorStep2.tsx
  src/pages/Personal/components/user/signIn/Senior/SeniorStep3.tsx
  src/pages/Personal/hooks/useAuth.ts
  src/pages/Personal/types/auth.ts
  src/routes/index.tsx
  src/shared/apis/axiosInstance.ts
Labels: feature, 소이

#68 [feat] 시니어 내정보 플로우
  src/pages/Personal/QuestionDetailPage.tsx
  src/pages/Personal/my/PersonalDeleteAccount.tsx
  src/pages/Personal/my/PersonalDeleteAccountDone.tsx
  src/pages/Personal/my/apply/ApplyDetail.tsx
  src/pages/Personal/my/apply/ApplyResults.tsx
  src/pages/Personal/my/info/BasicInfo.tsx
  src/pages/Personal/my/info/BasicInfoEdit.tsx
  src/pages/Personal/my/info/ExtraInfo.tsx
  src/pages/Personal/my/info/ExtraInfoEdit.tsx
  src/pages/Personal/my/info/PersonalInfo.tsx
  src/pages/Personal/my/info/PersonalPasswordEdit.tsx
  src/pages/Personal/my/info/PersonalPasswordEditDone.tsx
  src/routes/index.tsx
  src/shared/components/topbar/QuestionButton.tsx
  src/shared/components/topbar/menu/personal-menu/MainMenu.tsx
  src/shared/components/topbar/menu/personal-menu/PersonalMenu.tsx
  src/shared/components/topbar/menu/personal-menu/SeniorMyMenu.tsx
Labels: feature

#71 [feat] 토글 경로 수정
  src/shared/components/topbar/ToggleButton.tsx
  src/shared/components/topbar/Topbar.tsx
Labels: fix

#81 [feat] 보호자 내정보 플로우
  src/pages/Personal/my/PersonalPasswordEdit.tsx
  src/pages/Personal/my/PersonalPasswordEditDone.tsx
  src/pages/Personal/my/cares/care-seniors/CareSeniorDetail.tsx
  src/pages/Personal/my/cares/care-seniors/CareSeniors.tsx
  src/pages/Personal/my/seniors/apply/ApplyDetail.tsx
  src/pages/Personal/my/seniors/apply/ApplyResults.tsx
  src/pages/Personal/my/seniors/info/BasicInfo.tsx
  src/pages/Personal/my/seniors/info/BasicInfoEdit.tsx
  src/pages/Personal/my/seniors/info/ExtraInfo.tsx
  src/pages/Personal/my/seniors/info/ExtraInfoEdit.tsx
  src/pages/Personal/my/seniors/info/SeniorInfo.tsx
  src/routes/index.tsx
  src/shared/components/topbar/menu/personal-menu/CareMyMenu.tsx
  src/shared/components/topbar/menu/personal-menu/GuardianMyMenu.tsx
  src/shared/components/topbar/menu/personal-menu/MainMenu.tsx
  src/shared/components/topbar/menu/personal-menu/PersonalMenu.tsx
  src/shared/components/topbar/menu/personal-menu/SeniorMyMenu.tsx
Labels: feature

#83 [feat] 채용공고 post api 연결
  src/App.tsx
  src/index.css
  src/pages/Company/CompanyCreateJobPage.tsx
  src/pages/Company/types/job.ts
  src/shared/components/AddressSearchInput.tsx
  src/shared/components/EvidenceSection/ImageUploadButton.tsx
  src/shared/hooks/job/useJobGet.tsx
  src/shared/hooks/job/useJobPost.tsx
  src/shared/hooks/useImageUpload.ts
Labels: feature

#86 [feat] 일반유저 회원가입 연동, 아이디 및 비밀번호 찾기, 로그아웃 api 연동 / 카카오 로그인 연동
  src/App.tsx
  src/index.css
  src/pages/Personal/KakaoCallback.tsx
  src/pages/Personal/Login.tsx
  src/pages/Personal/LoginMain.tsx
  src/pages/Personal/SignIn.tsx
  src/pages/Personal/apis/auth.ts
  src/pages/Personal/components/user/FindAccount/IdFind.tsx
  src/pages/Personal/components/user/FindAccount/PasswordFind.tsx
  src/pages/Personal/components/user/signIn/Care/CareSignIn.tsx
  src/pages/Personal/components/user/signIn/Care/CareStep1.tsx
  src/pages/Personal/components/user/signIn/Care/CareStep2.tsx
  src/pages/Personal/components/user/signIn/Care/CareStep3.tsx
  src/pages/Personal/components/user/signIn/Care/CareStep4.tsx
  src/pages/Personal/components/user/signIn/Care/CareStep5.tsx
  src/pages/Personal/components/user/signIn/NextButton.tsx
  src/pages/Personal/components/user/signIn/Senior/SeniorSignIn.tsx
  src/pages/Personal/components/user/signIn/Senior/SeniorStep1.tsx
  src/pages/Personal/components/user/signIn/Senior/SeniorStep2.tsx
  src/pages/Personal/components/user/signIn/Senior/SeniorStep3.tsx
  src/pages/Personal/hooks/useAuth.ts
  src/pages/Personal/hooks/useLogout.ts
  src/pages/Personal/types/auth.ts
  src/pages/Personal/types/user.ts
  src/routes/index.tsx
  src/shared/apis/axiosInstance.ts
  src/shared/components/topbar/menu/MenuNavButton.tsx
  src/shared/components/topbar/menu/personal-menu/MainMenu.tsx
Labels: feature, 소이

#96 [feat] 기업 유저 계정 찾기 api 연동
  src/pages/Company/apis/companyAuth.ts
  src/pages/Company/components/FindAccount/IdFind.tsx
  src/pages/Company/components/FindAccount/PasswordFind.tsx
  src/pages/Company/hooks/useCompanyAuth.ts
  src/pages/Company/types/findAccount.ts
Labels: feature, 소이

#106 [Feat] 일자리 신청서 AI 답변 API 연동
  pnpm-lock.yaml
  src/pages/Company/ApplicationDetailPage.tsx
  src/pages/Personal/JobApplyPage.tsx
  src/pages/Personal/JobDraftsPage.tsx
  src/pages/Personal/apis/ai.ts
  src/pages/Personal/apis/applications.ts
  src/pages/Personal/apis/auth.ts
  src/pages/Personal/apis/files.ts
  src/pages/Personal/types/ai.ts
  src/pages/Personal/types/applications.ts
  src/pages/Personal/types/files.ts
  src/shared/components/NextButton.tsx
  src/shared/components/QuestionWriteFormSection.tsx
  src/shared/utils/sanitize.ts
Labels: feature, 연수

#109 [feat] 기업 받은 신청서 API
  src/pages/Company/ApplicationDetailPage.tsx
  src/pages/Company/ApplicationResultsPage.tsx
  src/pages/Company/ApplicationsPage.tsx
  src/pages/Company/apis/applications.ts
Labels: feature, 연수

#120 [fix] 배포환경에서 로그아웃 및 카카오 로그인 문제 해결
  src/shared/components/topbar/menu/company-menu/AfterLoginMainMenu.tsx
  src/shared/components/topbar/menu/personal-menu/CareMyMenu.tsx
  src/shared/components/topbar/menu/personal-menu/MainMenu.tsx
  vercel.json
Labels: fix, 소이

#126 [feat] 받은 신청서 디테일, 결과 공시 API 연결
  package.json
  pnpm-lock.yaml
  src/pages/Company/ApplicationDetailPage.tsx
  src/pages/Company/ApplicationResultsPage.tsx
  src/pages/Company/ApplicationsPage.tsx
  src/pages/Company/CompanyJobListPage.tsx
  src/pages/Company/apis/applications.ts
  src/pages/Company/hooks/useJobFlow.tsx
  src/routes/index.tsx
Labels: feature, 연수

#132 [feat] 시니어 내정보 플로우
  .gitignore
  package.json
  pnpm-lock.yaml
  src/pages/Company/my/CompanyDeleteAccount.tsx
  src/pages/Company/my/CompanyInfo.tsx
  src/pages/Company/my/JobPostRepost.tsx
  src/pages/Personal/my/cares/care-seniors/CareCheckApplicationDetail.tsx
  src/pages/Personal/my/cares/care-seniors/CareCheckApplicationResults.tsx
  src/pages/Personal/my/cares/care-seniors/SeniorApplicationResults.tsx
  src/pages/Personal/my/seniors/SeniorApplyDetail.tsx
  src/pages/Personal/my/seniors/SeniorApplyResults.tsx
  src/pages/Personal/my/seniors/info/BasicInfo.tsx
  src/pages/Personal/my/seniors/info/BasicInfoEdit.tsx
  src/pages/Personal/my/seniors/info/ExtraInfo.tsx
  src/pages/Personal/my/seniors/info/ExtraInfoEdit.tsx
  src/pages/Personal/my/seniors/info/SeniorInfo.tsx
  src/pages/Personal/types/userInfo.ts
  src/react-daum-postcode.d.ts
  src/routes/index.tsx
  src/shared/utils/userInfoUtils.ts
Labels: feature

#133 [chore] react-toastify 적용
  package.json
  pnpm-lock.yaml
  src/App.tsx
  src/pages/Company/ApplicationResultsPage.tsx
  src/pages/Company/CompanyCreateJobPage.tsx
  src/pages/Company/CompanyJobListPage.tsx
  src/pages/Company/CompanyLogin.tsx
  src/pages/Company/CompanySignin.tsx
  src/pages/Company/components/FindAccount/IdFind.tsx
  src/pages/Company/components/FindAccount/PasswordFind.tsx
  src/pages/Company/hooks/useCompanyAuth.ts
  src/pages/Company/hooks/useJobFlow.tsx
  src/pages/Company/my/CompanyDeleteAccount.tsx
  src/pages/Company/my/CompanyInfoEdit.tsx
  src/pages/Company/my/CompanyPasswordEdit.tsx
  src/pages/Personal/JobApplyPage.tsx
  src/pages/Personal/JobDetailPage.tsx
  src/pages/Personal/KakaoCallback.tsx
  src/pages/Personal/Login.tsx
  src/pages/Personal/components/user/FindAccount/IdFind.tsx
  src/pages/Personal/components/user/FindAccount/PasswordFind.tsx
  src/pages/Personal/components/user/signIn/Care/CareSignIn.tsx
  src/pages/Personal/components/user/signIn/Care/CareStep1.tsx
  src/pages/Personal/components/user/signIn/Care/CareStep2.tsx
  src/pages/Personal/components/user/signIn/Care/CareStep3.tsx
  src/pages/Personal/components/user/signIn/Care/CareStep4.tsx
  src/pages/Personal/components/user/signIn/Care/CareStep5.tsx
  src/pages/Personal/components/user/signIn/Senior/SeniorSignIn.tsx
  src/pages/Personal/components/user/signIn/Senior/SeniorStep1.tsx
  src/pages/Personal/components/user/signIn/Senior/SeniorStep2.tsx
  src/pages/Personal/components/user/signIn/Senior/SeniorStep3.tsx
  src/pages/Personal/hooks/useAddressSearch.ts
  src/pages/Personal/my/PersonalDeleteAccount.tsx
  src/pages/Personal/my/PersonalPasswordEdit.tsx
  src/pages/Personal/my/cares/care-seniors/LinkingSenior.tsx
  src/pages/Personal/my/cares/info/CareInfoEdit.tsx
  src/pages/Personal/my/seniors/info/SeniorInfo.tsx
  src/shared/apis/axiosInstance.ts
  src/shared/components/topbar/menu/personal-menu/LinkedSeniorList.tsx
  src/shared/hooks/useLogout.ts
Labels: add, chore, 소이

#149 [feat] 보호자 내정보 플로우
  src/global.d.ts
  src/index.css
  src/pages/Company/my/ClosedJobPosts.tsx
  src/pages/Company/my/ClosedJobRePostStep2.tsx
  src/pages/Company/my/ClosedJobRepostStep1.tsx
  src/pages/Company/my/JobPostRepost.tsx
  src/pages/Company/types/companyInfo.ts
  src/pages/Personal/ExtraQuestionsPage.tsx
  src/pages/Personal/my/cares/care-seniors/CareCheckApplicationDetail.tsx
  src/pages/Personal/my/cares/care-seniors/CareCheckApplicationResults.tsx
  src/pages/Personal/my/cares/care-seniors/SeniorExtraInfo.tsx
  src/pages/Personal/my/cares/care-seniors/SeniorExtraInfoEdit.tsx
  src/pages/Personal/my/seniors/SeniorApplyDetail.tsx
  src/pages/Personal/my/seniors/SeniorApplyResults.tsx
  src/pages/Personal/my/seniors/apply/ApplyResults.tsx
  src/pages/Personal/my/seniors/info/BasicInfoEdit.tsx
  src/pages/Personal/types/userInfo.ts
  src/routes/index.tsx
  src/shared/components/topbar/Topbar.tsx
  src/shared/components/topbar/menu/company-menu/CompanyMyMenu.tsx
  src/shared/components/topbar/menu/personal-menu/LinkedSeniorDetail.tsx
  src/shared/components/topbar/menu/personal-menu/MainMenu.tsx
Labels: feature

#153 [feat] 기업, 개인 로그인 전 요즘 뜨는 공고 api 연결
  README.md
  src/pages/Company/home/HomeBeforeLogin.tsx
  src/pages/Personal/apis/jobapi.ts
  src/pages/Personal/home/HomeAfterLogin.tsx
  src/pages/Personal/home/HomeBeforeLogin.tsx
  src/pages/Personal/home/PersonalHomePage.tsx
  src/pages/Personal/hooks/useTrendJob.tsx
  src/pages/Personal/types/jobs.ts
  vite.config.ts
Labels: feature, 보경

#157 [style] 메뉴바 구성 변경
  src/shared/components/topbar/menu/personal-menu/MainMenu.tsx
Labels: refactor, style, 보경

#160 [feat] 기업 마감 공고 리포스팅
  src/pages/Company/my/ClosedJobList.tsx
  src/pages/Company/my/ClosedJobPosts.tsx
  src/pages/Company/my/ClosedJobRePostStep2.tsx
  src/pages/Company/my/ClosedJobRepostDetail.tsx
  src/pages/Company/my/ClosedJobRepostStep1.tsx
  src/pages/Company/my/RePostStep2.tsx
  src/pages/Company/my/RepostStep1.tsx
  src/pages/Company/types/companyInfo.ts
  src/pages/Personal/my/seniors/SeniorApplyResults.tsx
  src/routes/index.tsx
  src/shared/components/topbar/menu/company-menu/CompanyMyMenu.tsx
Labels: feature

#159 [feat] 업데이트AI API 연동 추가
  src/pages/Company/home/HomeAfterLogin.tsx
  src/pages/Company/hooks/usePopularJobs.ts
  src/pages/Personal/JobApplyPage.tsx
  src/pages/Personal/apis/ai.ts
  src/pages/Personal/apis/applications.ts
  src/pages/Personal/apis/guardian.ts
  src/pages/Personal/apis/questionsDelegate.ts
  src/pages/Personal/types/applications.ts
Labels: feature, 연수

#162 [style] 메뉴바 css 수정
  src/shared/assets/logo.svg
  src/shared/assets/popular-dummy1.png
  src/shared/components/topbar/Logo.tsx
  src/shared/components/topbar/menu/company-menu/AfterLoginMainMenu.tsx
  src/shared/components/topbar/menu/company-menu/CompanyMenu.tsx
  src/shared/components/topbar/menu/personal-menu/MainMenu.tsx
  src/shared/components/topbar/menu/personal-menu/PersonalMenu.tsx
Labels: style

#174 [feat] 개인 일자리 신청 폼 ui 구현
  src/pages/Personal/JobApplyExtendedForm.tsx
  src/pages/Personal/JobDetailPage.tsx
  src/pages/Personal/home/HomeAfterLogin.tsx
  src/pages/Personal/types/jobapplication.ts
Labels: feature, 보경

#182 [fix] 기업 신청결과 상세 페이지 에러 수정
  src/pages/Personal/JobDraftsPage.tsx
  src/pages/Personal/my/cares/care-seniors/CareCheckApplicationDetail.tsx
  src/pages/Personal/my/seniors/SeniorApplyDetail.tsx
  src/pages/Personal/types/userInfo.ts
  src/shared/components/field/ImageField.tsx
  src/shared/components/field/TextField.tsx
  src/shared/components/topbar/menu/company-menu/AfterLoginMainMenu.tsx
Labels: fix
